### ISSUE TITLE
semtech udp parsing error invalid Json string for TxAck frame

### ISSUE THREAD

**Issue by disk91** [helium/semtech-udp#68]
It seems that some semtech json stuff from my kerlink iFemToCell ( not helium hotspot, vanilia iFemToCell) is not correctly managed by the gateway-rs software.

```
INFO uplink @2523639308 us, 904.90 MHz, Ok(DataRate(SF10, BW125)), snr: -8.2, rssi: -123, len: 23 from 72:76:FF:00:39:03:00:AE, module: gateway
 INFO rx1 downlink @2528639308 us, 926.30 MHz, DataRate(SF10, BW500), len: 17 via 72:76:FF:00:39:03:00:AE, module: gateway
 WARN ignoring semtech udp parsing error invalid Json string for TxAck frame: . JsonError: expected value at line 1 column 1, raw bytes [2, 139, 165, 5, 114, 118, 255, 0, 57, 3, 0, 174, 0], module: gateway
 WARN ignoring rx1 downlink error: SendTimeout, module: gateway
```

**Comment by disk91** [comment]
here is what I see as json, I assume it is somewhere else: 
```
 {"rxpk":[{"tmst":1337602716,"time":"2022-07-18T06:57:39Z","chan":0,"rfch":0,"freq":903.900000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":-4.5,"rssi":-125,"size":23,"data":"AJouPdfv+YFgmGG/w5b5gWDh2Ut7KjY="}]
```

**Comment by madninja** [comment]
> here is what I see as json, I assume it is somewhere else:
> 
> ```
>  {"rxpk":[{"tmst":1337602716,"time":"2022-07-18T06:57:39Z","chan":0,"rfch":0,"freq":903.900000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":-4.5,"rssi":-125,"size":23,"data":"AJouPdfv+YFgmGG/w5b5gWDh2Ut7KjY="}]
> ```

Thanks.. looks like @lthiery has a fix in the works. Looks like this forwarder encodes the null in a cstring somehow :/
