### ISSUE TITLE
Valid TX_ACKs are not decoded

### ISSUE THREAD

**Issue by timcooijmans** [helium/semtech-udp#77]
The SX1302 PacketForwarder Semtech GWMP protocol defines all fields in the `txpk_ack` JSON-structure in the `TX_ACK` packet as optional. (source: https://github.com/Lora-net/sx1302_hal/blob/master/packet_forwarder/PROTOCOL.md#55-tx_ack-packet)

The result is that valid packets such as `{"txpk_ack":{}}` are not decoded and an error is thrown. In practice we also see `{"txpk_ack":{"error":""}}` but we can debate if that's a valid packet or not. 

Test to show issue:
```rust
fn tx_ack_deser_minimal() {
    let json = "{\"txpk_ack\":{}}";
    let parsed: Data = serde_json::from_str(json).expect("Error parsing tx_ack");
    if let Err(_) = parsed.get_result() {
        assert!(false);
    }
}
```

**Comment by lthiery** [comment]
resolved in #78
